all : addascatterer2netCDF.cc
	g++ -std=c++1y addascatterer2netCDF.cc -o addascatterer2netCDF -O2 -I ../include/ -Wall -Weffc++ -I /opt/netcdf-cxx4-4.3.0/include/ -L /opt/netcdf-cxx4-4.3.0/lib -lnetcdf_c++4
#	g++ -std=c++1y addascatterer2netCDFfast.cc -o addascatterer2netCDFfast -O2  -fopenmp  -I ../include/  -Wall -Weffc++ -I /opt/netcdf-cxx4-4.3.0/include/ -L /opt/netcdf-cxx4-4.3.0/lib -lnetcdf_c++4
