all : netCDF2addascatterer.cc
	g++ -std=c++1y netCDF2addascatterer.cc -o netCDF2addascatterer -O2 -I ../include/ -Wall -Weffc++ -I /opt/netcdf-cxx4-4.3.0/include/ -L /opt/netcdf-cxx4-4.3.0/lib -lnetcdf_c++4
	#g++ -std=c++1y addascatterer2netCDF.cc -o addascatterer2netCDF -g -I ../include/ -Wall -Weffc++ -I /opt/netcdf-cxx4-4.3.0/include/ -L /opt/netcdf-cxx4-4.3.0/lib -lnetcdf_c++4
